PIH/openmrs-config-pihsl

configuration/pih/pih-config-sierraLeone.json

See https://github.com/PIH/openmrs-module-pihcore/blob/9375d67f308288387fda5e115a16091de75ea4f9/api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java#L120

UHM-4683 Move Location Tag Setup out of PIH Core and into Config

---

configuration/pih/htmlforms/mentalHealth.xml

Updated 4 concepts.  Unfortunately this will require an update to the report AND loss of the previous data.  It's not possible to migrate the old data.

SL-211 Fixed suicide concepts on Mental Health form

---

configuration/pih/htmlforms/mentalHealth.xml

Modified MH form to align with the Koidu Government Hospital Mental health patient assessment form

Mental health patient assessment form changes

---

configuration/locations/locations.csv

For lab results form but also tweaked for other tags/locations

SL-295 Updated locations with Lab Results form

---

configuration/pih/htmlforms/mentalHealthFollowup_v1.0.xml

I just updated the mental health followup form to use drug orders.

SL-393, migrate to drug orders

---

configuration/addresshierarchy/addressConfiguration.xml
configuration/addresshierarchy/sierra_leone_address_hierarchy_entries.csv
configuration/pih/pih-config-sierraLeone.json

@mseaton , here is the config parameter you suggested we add for the AddressHierarchyDisplayTemplate

UHM-7478, implement showCountryInAddressHiercharchy config parameter

---

configuration/pih/htmlforms/section-delivery.xml

I have just included in this form the same code that was in the ANC followup form which was working correctly. Now the EDD is displayed correctly on the Delivery form as well:

SL-443, refactor estimated delivery date calculation

---

configuration/pih/htmlforms/patientRegistration-localAddress.xml

This PR fixes the problem with the quick search address update, and also adds the phone number to the list of editable fields:

SL-454, correct field name

---

configuration/pih/htmlforms/delivery_v2.0.xml
configuration/pih/htmlforms/section-delivery.xml
configuration/pih/htmlforms/section-delivery_v1.0.xml
configuration/pih/htmlforms/section-delivery_v1.1.xml
configuration/pih/htmlforms/section-delivery_v2.0.xml

Adding delivery.xml (V3.0) requires new and upgraded files for delivery*.xml and section-delivery*.xml

SL-477 Updates to the delivery form(s) for Version 3.0

---

configuration/locations/locations-site-kgh-test.csv
configuration/pih/pih-config-sierraLeone-kgh-test.json
configuration/queues/queues-site-kgh-test.csv

UHM-7622, add MCOE queue services

---

configuration/programworkflows/ncd.csv
configuration/programworkflowstates/ncd.csv

There is also a PR for pihemr and zl.   Liberia and CES already had custom files.

UHM-7707 Retired the NCD workflow/states

---

configuration/pih/htmlforms/triage.xml

Added a simple queue selection and priority:

SL-553: set queue entry priority

---

configuration/pih/htmlforms/triage.xml

@lnball , here is my attempt to create one evaluation question and to render correctly. Looking forward to see your recommendation on the proper way to model those questions. Thanks!

SL-553, add evaluation question

---

configuration/pih/htmlforms/section-anc-followup.xml
configuration/pih/htmlforms/section-anc-intake.xml
configuration/pih/htmlforms/section-diabetes.xml
configuration/pih/htmlforms/section-heart-failure.xml
configuration/pih/htmlforms/section-hospital.xml
configuration/pih/htmlforms/section-hypertension.xml
configuration/pih/htmlforms/section-kidney.xml
configuration/pih/htmlforms/section-liver.xml
configuration/pih/htmlforms/section-lung.xml
configuration/pih/htmlforms/section-palliative.xml
configuration/pih/htmlforms/section-sickle-cell.xml

It looks ok, but every few times of pressing the buttons, there's a spinning wheel and the page doesn't load.  I'll document on the ticket.

SL-562 Added the bottom navigation buttons

---

configuration/reports/reportdescriptors/dataexports/sql/ncd_encounter.sql

Reverts PIH/openmrs-config-pihsl#159

Revert "SL-651 add referred to surgery"

---

configuration/locations/locations.csv

Removed Vitals form for KGH Triage location

SL-641 Removed vitals form for KGH Triage location

---

configuration/pih/htmlforms/nicuTriage.xml

Added one lab test (MRDT) but let's use this to review Sulaiman's code AND my additions for the improved layout.
Improve radio button layout:
* add paragraph with class=side-by-side
* add answerSeparator
* add line break after label <br/>
In /home/ball/workspace/openmrs-config-pihsl, I ran these commands to create a branch with this change:
* "git status" (check the branch/master)
* "git pull" (get all the latest master code)
* "git checkout -b SL-636" (create new branch SL-636)
* "git add ." (add the updated nicuTriage.xml form)
* "git commit -m "SL-636 Added MRDT to nicu triage form" (commit file to branch)
* "git push --set-upstream origin SL-636" (push code to branch)
Create a pull request for 'SL-636' on GitHub by visiting:
https://github.com/PIH/openmrs-config-pihsl/pull/new/SL-636 …

SL-636 Added Malaria rapid test

---

configuration/pih/pih-dispositions-sierraLeone-mcoe.json

See ticket for question...
https://pihemr.atlassian.net/browse/SL-675

SL-675 Added admit for NICU triage form

---

configuration/frontend/config.json
constants.yml

Changes to config for corresponding PR in esm-ward-app:
https://github.com/openmrs/openmrs-esm-patient-management/pull/1339

UHM-8202 - refactor ward app config

---

configuration/pih/liquibase/liquibase-sierra_leone.xml

Added this changeset to the SL config.  
Unfortunately the changeset didn't run on my local SDK and I don't know why.  I searched in the log AND the liquibasechangelog table.
Feel free to review my code AND explain why it didn't run locally @mogoodrich

SL-762 Add 20241028-void-mch-patient-program changeset for SL

---

configuration/frontend/config.json

Corresponding change in openrms-esm-patient-management:
https://github.com/openmrs/openmrs-esm-patient-management/pull/1359

UHM-8237 configure links in workspace vitals header to hide

---

configuration/pih/liquibase/liquibase-sierra_leone.xml

Migrate the old/duplicate HIV test/counselling question IF there is no obs for the original HIV counseling question

SL-815 Migrate the duplicate HIV question on 2 ANC forms

---

configuration/pih/htmlforms/laborDeliverySummary.xml

@mseaton and @mogoodrich , here for FSB and MSB I specifically set the hidden obs to "Do not register":

SL-877: do not register FSB and MSB

---

configuration/pih/htmlforms/vitalsWithGlucose.xml
configuration/pih/liquibase/liquibase-sierra_leone.xml
configuration/pih/liquibase/sql/migrate_vitals_fbg_obs.sql

@mogoodrich , I just used the SQL script you wrote to migrate the FBG obs from the Vitals encounter. Thanks!

SL-913: migrate FBG obs to use a new concept

---

configuration/frontend/config.json

https://pihemr.atlassian.net/browse/UHM-8242

UHM-8242 change O3 appointments check-in button redirect URL

---

configuration/pih/htmlforms/section-kidney.xml

Moved the end tag for obsgroup for the kidney followup indicators.

SL-1021 Include all kidney followup indicators in obsgroup
